# L Investigation Framework - License

## THE CODE - Moral Foundation

*"Never violate a woman, nor harm a child.*
*Do not lie, cheat or steal. These things are for lesser men.*
*Protect the weak against the evil strong and never allow thoughts of gain to lead you into the pursuit of evil.*
*Never back away from an enemy, either fight or surrender.*
*It is not enough to say I will not be evil, evil must be fought wherever it is found."*

**— David Gemmell, The Drenai Code**

---

## Purpose

This software exists to **fight evil wherever it is found.**

This is an investigative tool for:
- OSINT investigation
- Evidence analysis
- Criminal pattern detection
- Protection of the weak
- Pursuit of truth and justice

**This software is bound by The Code:**
- Protect the weak (anonymize victims, prioritize safety)
- Report truth (cite sources, no fabrication)
- Never lie (distinguish fact vs hypothesis)
- Fight evil (follow evidence wherever it leads)

---

## Permitted Uses

✅ **ALLOWED:**
- Criminal investigations (authorized)
- OSINT research
- Evidence preservation
- Academic/educational purposes
- Journalistic investigation
- Legal discovery
- Pattern analysis of criminal activity
- Protection of vulnerable populations

---

## Prohibited Uses

❌ **FORBIDDEN:**
- Violation of privacy without legal basis
- Doxxing innocent individuals
- Fabrication of evidence
- Harassment or intimidation
- Revenge or personal vendetta
- Profit from harm to others
- Any use that violates The Code

**"Never allow thoughts of gain to lead you into the pursuit of evil."**

---

## MIT License

Copyright (c) 2025 Flow

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**The above copyright notice, this moral foundation, and The Code shall be included in all
copies or substantial portions of the Software.**

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

---

## Chain of Custody

All evidence generated by this system includes:
- SHA256 verification hashes
- Source document citations
- Collection timestamps
- Analysis methodology
- Moral foundation statement

**Truth. Justice. Protection of the weak.**

---

*"Evil must be fought wherever it is found."*
**This is The Code. This is why we build.**
